spring:
  application:
    name: authentication-service
  data:
    mongodb:
      database: signals
      port: 27017
      host: localhost

server:
  port: 8001
  error:
    include-stacktrace: on_param
