spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:9001/signals
    username: signals
    password: signals

server:
  port: 8001
  error:
    include-stacktrace: on_param
