version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: signals
      POSTGRES_PASSWORD: signals
      POSTGRES_DB: signals
    ports:
      - "9001:5432/tcp"
    networks:
      - signals
    deploy:
      restart_policy:
        condition: on-failure

networks:
  signals:
